### ISSUE TITLE
Skyline does not exit gracefully when it encounters an error with CUPTI_INSUFFICIENT_PRIVILEGES

### ISSUE THREAD

**Issue by michaelshin** [CentML/skyline#27]
I have a docker container without sufficient privileges for CUPTI and Skyline just hangs and does not return anything. Not sure if Skyline should handle this or if Habitat should

**Comment by jimgao1** [comment]
If I recall correctly only Habitat uses CUPTI. If that's the case, this error should be reported when skyline attempts to invoke Habitat. I believe Skyline has existing mechanisms to report errors to the frontend. 

Will take a look at this.

**Comment by michaelshin** [comment]
I'll close this issue here and move it over to Habitat then
